server:
  port: 9002
  
spring:
  application:
    name: welcome-app
  boot:
    admin:
      client:
        url: http://localhost:9006
  zipkin:
    base-url: htttp://127.0.0.1:9411/
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    

  endpoint:
     shutdown:
       enabled: true  